[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "eigenlayer-middleware/=lib/mach-avs/contracts/lib/eigenlayer-middleware/src/",
    "eigenlayer-core/=lib/mach-avs/contracts/lib/eigenlayer-middleware/lib/eigenlayer-contracts/src/",
    "@openzeppelin/=lib/mach-avs/contracts/lib/eigenlayer-middleware/lib/openzeppelin-contracts/",
    "@openzeppelin-upgrades/=lib/mach-avs/contracts/lib/eigenlayer-middleware/lib/openzeppelin-contracts-upgradeable/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
